### PR TITLE
Feature/1 rename articles and snippets

### PR DESCRIPTION
**Pull request by mmoio**
# Overview

Please include a summary of your contribution.

# Checklist

## General

- [x] I have verified that all 3 components of the app are active after running `npm start`: the React server at http://localhost:490001, the backend server at http://localhost:49000, and the World Scribe 2 application window.
- [x] I have verified that communication between the application and the backend server is still working (e.g. by verifying that the application is making HTTP requests and receiving responses). 

## UI Changes

- [x] I have verified that all affected components are visible and responsive when the application window is maximized.
- [x] Where applicable, I display informative error messages to the user.

## Settings Changes

- [x] I have verified that ALL settings are saved properly between app sessions.

- [x] **For new settings:** I have verified that my new setting(s) appear on both the Initial Setup page and the App Settings page.

### CODE REVIEW

**Comment by MarquisLP** [comment]
LGTM! The routes work well and adhere to the style of the other routes.

My only suggestion is to **change the route names from `/rename` to `/name`**. This would be more in-line with the REST principle of routes referring to resources. In this case, it can be said that we are `PATCH`ing the `name` resource of an Article/Snippet/Category. An example of an existing route that follows this principle is `PATCH /api/categories/:categoryId/description/`.

**Review by MarquisLP — CHANGES_REQUESTED** [review]
Please see the comment above.

**Comment by mmoio** [comment]
Done! Changed the routes to /name instead of /rename

**Review by MarquisLP — APPROVED** [review]
LGTM!

**Pull request merged**
